<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE database [
  <!ELEMENT database    (description,record+)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT record    (voornaam,geslacht,t8306,n8589,n9094,n9599,n0004,p8589,p9094,p9599,p0004)>
  <!ELEMENT voornaam      (#PCDATA)>
  <!ELEMENT geslacht    (#PCDATA)>
  <!ELEMENT t8306 (#PCDATA)>
  <!ELEMENT n8589   (#PCDATA)>
  <!ELEMENT n9094   (#PCDATA)>
  <!ELEMENT n9599   (#PCDATA)>
  <!ELEMENT n0004   (#PCDATA)>
  <!ELEMENT p8589   (#PCDATA)>
  <!ELEMENT p9094   (#PCDATA)>
  <!ELEMENT p9599   (#PCDATA)>
  <!ELEMENT p0004   (#PCDATA)>
]>
<database>
<description>Dit databestand geeft een overzicht van de voornamen die in Nederland 
tussen 1983 en 2006 27 keer of vaker gegeven zijn volgens de administratie van de
Sociale Verzekeringsbank. Toelichting: t8306 (aantal kinderen in de periode 1983-2006);
n8589 (aantal kinderen in de periode 1985-1989), enzovoort tot n0004 (aantal kinderen 
in de periode 2000-2004);p8589 (percentage kinderen x 10.000 in de periode 1985-1989), 
enzovoort tot p0004.     
</description>
<record><voornaam>Thomas</voornaam><geslacht>M</geslacht><t8306>26794</t8306><n8589>4856</n8589><n9094>6559</n9094><n9599>6412</n9599><n0004>5897</n0004><p8589>8972</p8589><p9094>11424</p9094><p9599>11760</p9599><p0004>11324</p0004></record>
<record><voornaam>Johannes</voornaam><geslacht>M</geslacht><t8306>24177</t8306><n8589>7618</n8589><n9094>5719</n9094><n9599>3860</n9599><n0004>2671</n0004><p8589>14075</p8589><p9094>9961</p9094><p9599>7079</p9599><p0004>5129</p0004></record>
<record><voornaam>Tim</voornaam><geslacht>M</geslacht><t8306>23730</t8306><n8589>4657</n8589><n9094>5367</n9094><n9599>5781</n9599><n0004>5155</n0004><p8589>8605</p8589><p9094>9348</p9094><p9599>10602</p9599><p0004>9899</p0004></record>
<record><voornaam>Kevin</voornaam><geslacht>M</geslacht><t8306>22894</t8306><n8589>5449</n8589><n9094>7165</n9094><n9599>5353</n9599><n0004>3211</n0004><p8589>10068</p8589><p9094>12479</p9094><p9599>9818</p9599><p0004>6166</p0004></record>
<record><voornaam>Sanne</voornaam><geslacht>V</geslacht><t8306>22339</t8306><n8589>4836</n8589><n9094>4365</n9094><n9599>5432</n9599><n0004>5090</n0004><p8589>9349</p8589><p9094>7988</p9094><p9599>10478</p9599><p0004>10267</p0004></record>
<record><voornaam>Maria</voornaam><geslacht>V</geslacht><t8306>21425</t8306><n8589>6866</n8589><n9094>5098</n9094><n9599>3263</n9599><n0004>2382</n0004><p8589>13274</p8589><p9094>9329</p9094><p9599>6294</p9599><p0004>4804</p0004></record>
<record><voornaam>Jeroen</voornaam><geslacht>M</geslacht><t8306>21271</t8306><n8589>6551</n8589><n9094>6174</n9094><n9599>3839</n9599><n0004>1717</n0004><p8589>12104</p8589><p9094>10753</p9094><p9599>7041</p9599><p0004>3297</p0004></record>
<record><voornaam>Laura</voornaam><geslacht>V</geslacht><t8306>20681</t8306><n8589>4373</n8589><n9094>5634</n9094><n9599>5438</n9599><n0004>3068</n0004><p8589>8454</p8589><p9094>10310</p9094><p9599>10489</p9599><p0004>6188</p0004></record>
<record><voornaam>Jan</voornaam><geslacht>M</geslacht><t8306>20483</t8306><n8589>5646</n8589><n9094>4612</n9094><n9599>3839</n9599><n0004>2981</n0004><p8589>10432</p8589><p9094>8033</p9094><p9599>7041</p9599><p0004>5724</p0004></record>
<record><voornaam>Anne</voornaam><geslacht>V</geslacht><t8306>20461</t8306><n8589>3865</n8589><n9094>5077</n9094><n9599>5074</n9599><n0004>4371</n0004><p8589>7472</p8589><p9094>9291</p9094><p9599>9787</p9599><p0004>8816</p0004></record>
<record><voornaam>Dennis</voornaam><geslacht>M</geslacht><t8306>19105</t8306><n8589>5714</n8589><n9094>5333</n9094><n9599>3609</n9599><n0004>1617</n0004><p8589>10558</p8589><p9094>9289</p9094><p9599>6619</p9599><p0004>3105</p0004></record>
<record><voornaam>Kim</voornaam><geslacht>V</geslacht><t8306>18831</t8306><n8589>5115</n8589><n9094>3623</n9094><n9599>3766</n9599><n0004>3246</n0004><p8589>9889</p8589><p9094>6630</p9094><p9599>7264</p9599><p0004>6547</p0004></record>
<record><voornaam>Mark</voornaam><geslacht>M</geslacht><t8306>18616</t8306><n8589>5941</n8589><n9094>4660</n9094><n9599>3035</n9599><n0004>1807</n0004><p8589>10977</p8589><p9094>8116</p9094><p9599>5566</p9599><p0004>3470</p0004></record>
<record><voornaam>Niels</voornaam><geslacht>M</geslacht><t8306>18127</t8306><n8589>3612</n8589><n9094>4049</n9094><n9599>4176</n9599><n0004>3756</n0004><p8589>6674</p8589><p9094>7052</p9094><p9599>7659</p9599><p0004>7213</p0004></record>
<record><voornaam>Lisa</voornaam><geslacht>V</geslacht><t8306>17578</t8306><n8589>1277</n8589><n9094>5045</n9094><n9599>5286</n9599><n0004>4402</n0004><p8589>2469</p8589><p9094>9232</p9094><p9599>10196</p9599><p0004>8879</p0004></record>
<record><voornaam>Robin</voornaam><geslacht>M</geslacht><t8306>17299</t8306><n8589>3716</n8589><n9094>5067</n9094><n9599>3971</n9599><n0004>3143</n0004><p8589>6866</p8589><p9094>8825</p9094><p9599>7283</p9599><p0004>6036</p0004></record>
<record><voornaam>Tom</voornaam><geslacht>M</geslacht><t8306>17139</t8306><n8589>3045</n8589><n9094>4417</n9094><n9599>4177</n9599><n0004>3537</n0004><p8589>5626</p8589><p9094>7693</p9094><p9599>7661</p9599><p0004>6792</p0004></record>
<record><voornaam>Iris</voornaam><geslacht>V</geslacht><t8306>16984</t8306><n8589>2043</n8589><n9094>4490</n9094><n9599>4565</n9599><n0004>4082</n0004><p8589>3950</p8589><p9094>8217</p9094><p9599>8805</p9599><p0004>8233</p0004></record>
<record><voornaam>Anna</voornaam><geslacht>V</geslacht><t8306>16963</t8306><n8589>3534</n8589><n9094>3512</n9094><n9599>3352</n9599><n0004>3704</n0004><p8589>6832</p8589><p9094>6427</p9094><p9599>6466</p9599><p0004>7471</p0004></record>
<record><voornaam>Rick</voornaam><geslacht>M</geslacht><t8306>16905</t8306><n8589>3262</n8589><n9094>4374</n9094><n9599>4307</n9599><n0004>3587</n0004><p8589>6027</p8589><p9094>7618</p9094><p9599>7899</p9599><p0004>6888</p0004></record>
<record><voornaam>Johanna</voornaam><geslacht>V</geslacht><t8306>16690</t8306><n8589>5234</n8589><n9094>3914</n9094><n9599>2659</n9599><n0004>1902</n0004><p8589>10119</p8589><p9094>7163</p9094><p9599>5129</p9599><p0004>3836</p0004></record>
<record><voornaam>Nick</voornaam><geslacht>M</geslacht><t8306>16672</t8306><n8589>2789</n8589><n9094>4563</n9094><n9599>4283</n9599><n0004>3429</n0004><p8589>5153</p8589><p9094>7948</p9094><p9599>7855</p9599><p0004>6585</p0004></record>
<record><voornaam>Sander</voornaam><geslacht>M</geslacht><t8306>16484</t8306><n8589>4503</n8589><n9094>3644</n9094><n9599>3463</n9599><n0004>2673</n0004><p8589>8320</p8589><p9094>6347</p9094><p9599>6351</p9599><p0004>5133</p0004></record>
<record><voornaam>Martijn</voornaam><geslacht>M</geslacht><t8306>16418</t8306><n8589>4394</n8589><n9094>3999</n9094><n9599>3542</n9599><n0004>2263</n0004><p8589>8119</p8589><p9094>6965</p9094><p9599>6496</p9599><p0004>4346</p0004></record>
<record><voornaam>Bart</voornaam><geslacht>M</geslacht><t8306>16226</t8306><n8589>3970</n8589><n9094>4011</n9094><n9599>3478</n9599><n0004>2568</n0004><p8589>7335</p8589><p9094>6986</p9094><p9599>6379</p9599><p0004>4931</p0004></record>
<record><voornaam>Daan</voornaam><geslacht>M</geslacht><t8306>15599</t8306><n8589>1507</n8589><n9094>2416</n9094><n9599>3879</n9599><n0004>5486</n0004><p8589>2784</p8589><p9094>4208</p9094><p9599>7114</p9599><p0004>10535</p0004></record>
<record><voornaam>Michael</voornaam><geslacht>M</geslacht><t8306>14822</t8306><n8589>5227</n8589><n9094>4012</n9094><n9599>2208</n9599><n0004>1241</n0004><p8589>9658</p8589><p9094>6988</p9094><p9599>4050</p9599><p0004>2383</p0004></record>
<record><voornaam>Stefan</voornaam><geslacht>M</geslacht><t8306>14721</t8306><n8589>4622</n8589><n9094>4175</n9094><n9599>2578</n9599><n0004>1542</n0004><p8589>8540</p8589><p9094>7272</p9094><p9599>4728</p9599><p0004>2961</p0004></record>
<record><voornaam>Anouk</voornaam><geslacht>V</geslacht><t8306>14596</t8306><n8589>2144</n8589><n9094>3263</n9094><n9599>3886</n9599><n0004>3464</n0004><p8589>4145</p8589><p9094>5971</p9094><p9599>7496</p9599><p0004>6987</p0004></record>
<record><voornaam>Daniël</voornaam><geslacht>M</geslacht><t8306>14580</t8306><n8589>2857</n8589><n9094>3353</n9094><n9599>3163</n9599><n0004>2885</n0004><p8589>5279</p8589><p9094>5840</p9094><p9599>5801</p9599><p0004>5540</p0004></record>
<record><voornaam>Lars</voornaam><geslacht>M</geslacht><t8306>14322</t8306><n8589>1230</n8589><n9094>2493</n9094><n9599>4042</n9599><n0004>4622</n0004><p8589>2273</p8589><p9094>4342</p9094><p9599>7413</p9599><p0004>8876</p0004></record>
<record><voornaam>Mike</voornaam><geslacht>M</geslacht><t8306>14226</t8306><n8589>2018</n8589><n9094>4140</n9094><n9599>3927</n9599><n0004>2883</n0004><p8589>3729</p8589><p9094>7211</p9094><p9599>7202</p9599><p0004>5536</p0004></record>
<record><voornaam>Wouter</voornaam><geslacht>M</geslacht><t8306>14128</t8306><n8589>3371</n8589><n9094>3576</n9094><n9599>2876</n9599><n0004>2306</n0004><p8589>6228</p8589><p9094>6228</p9094><p9599>5275</p9599><p0004>4428</p0004></record>
<record><voornaam>Eva</voornaam><geslacht>V</geslacht><t8306>13855</t8306><n8589>2108</n8589><n9094>2768</n9094><n9599>3297</n9599><n0004>3472</n0004><p8589>4075</p8589><p9094>5066</p9094><p9599>6359</p9599><p0004>7003</p0004></record>
<record><voornaam>Ruben</voornaam><geslacht>M</geslacht><t8306>13824</t8306><n8589>2012</n8589><n9094>3091</n9094><n9599>3556</n9599><n0004>3304</n0004><p8589>3717</p8589><p9094>5384</p9094><p9599>6522</p9599><p0004>6345</p0004></record>
<record><voornaam>Willem</voornaam><geslacht>M</geslacht><t8306>13599</t8306><n8589>3566</n8589><n9094>3019</n9094><n9599>2764</n9599><n0004>2035</n0004><p8589>6589</p8589><p9094>5258</p9094><p9599>5069</p9599><p0004>3908</p0004></record>
<record><voornaam>Linda</voornaam><geslacht>V</geslacht><t8306>13474</t8306><n8589>5552</n8589><n9094>2900</n9094><n9599>1284</n9599><n0004>639</n0004><p8589>10734</p8589><p9094>5307</p9094><p9599>2477</p9599><p0004>1289</p0004></record>
<record><voornaam>Jeffrey</voornaam><geslacht>M</geslacht><t8306>13370</t8306><n8589>3930</n8589><n9094>4419</n9094><n9599>2686</n9599><n0004>1066</n0004><p8589>7261</p8589><p9094>7697</p9094><p9599>4926</p9599><p0004>2047</p0004></record>
<record><voornaam>Roy</voornaam><geslacht>M</geslacht><t8306>13356</t8306><n8589>4049</n8589><n9094>3832</n9094><n9599>2435</n9599><n0004>1487</n0004><p8589>7481</p8589><p9094>6674</p9094><p9599>4466</p9599><p0004>2855</p0004></record>
<record><voornaam>Michelle</voornaam><geslacht>V</geslacht><t8306>13344</t8306><n8589>2422</n8589><n9094>4770</n9094><n9599>3344</n9599><n0004>1959</n0004><p8589>4682</p8589><p9094>8729</p9094><p9599>6450</p9599><p0004>3951</p0004></record>
<record><voornaam>Bas</voornaam><geslacht>M</geslacht><t8306>13136</t8306><n8589>2136</n8589><n9094>3256</n9094><n9599>3288</n9599><n0004>2795</n0004><p8589>3947</p8589><p9094>5671</p9094><p9599>6030</p9599><p0004>5367</p0004></record>
<record><voornaam>Max</voornaam><geslacht>M</geslacht><t8306>13082</t8306><n8589>587</n8589><n9094>2207</n9094><n9599>4319</n9599><n0004>4612</n0004><p8589>1085</p8589><p9094>3844</p9094><p9599>7921</p9599><p0004>8856</p0004></record>
<record><voornaam>Bram</voornaam><geslacht>M</geslacht><t8306>13072</t8306><n8589>1697</n8589><n9094>2389</n9094><n9599>3336</n9599><n0004>3802</n0004><p8589>3135</p8589><p9094>4161</p9094><p9599>6118</p9599><p0004>7301</p0004></record>
<record><voornaam>Patrick</voornaam><geslacht>M</geslacht><t8306>13043</t8306><n8589>4227</n8589><n9094>3673</n9094><n9599>2311</n9599><n0004>860</n0004><p8589>7810</p8589><p9094>6397</p9094><p9599>4238</p9599><p0004>1651</p0004></record>
<record><voornaam>Jasper</voornaam><geslacht>M</geslacht><t8306>13037</t8306><n8589>2301</n8589><n9094>3114</n9094><n9599>3014</n9599><n0004>2809</n0004><p8589>4251</p8589><p9094>5424</p9094><p9599>5528</p9599><p0004>5394</p0004></record>
<record><voornaam>Lotte</voornaam><geslacht>V</geslacht><t8306>12772</t8306><n8589>1539</n8589><n9094>2390</n9094><n9599>3436</n9599><n0004>3665</n0004><p8589>2975</p8589><p9094>4374</p9094><p9599>6628</p9599><p0004>7392</p0004></record>
<record><voornaam>Hendrik</voornaam><geslacht>M</geslacht><t8306>12610</t8306><n8589>3605</n8589><n9094>2834</n9094><n9599>2246</n9599><n0004>1689</n0004><p8589>6661</p8589><p9094>4936</p9094><p9599>4119</p9599><p0004>3243</p0004></record>
<record><voornaam>Cornelis</voornaam><geslacht>M</geslacht><t8306>12564</t8306><n8589>3494</n8589><n9094>2934</n9094><n9599>2333</n9599><n0004>1728</n0004><p8589>6456</p8589><p9094>5110</p9094><p9599>4279</p9599><p0004>3318</p0004></record>
<record><voornaam>Thijs</voornaam><geslacht>M</geslacht><t8306>12332</t8306><n8589>1889</n8589><n9094>2124</n9094><n9599>2695</n9599><n0004>3304</n0004><p8589>3490</p8589><p9094>3699</p9094><p9599>4943</p9599><p0004>6345</p0004></record>
<record><voornaam>Pieter</voornaam><geslacht>M</geslacht><t8306>12311</t8306><n8589>3274</n8589><n9094>2723</n9094><n9599>2302</n9599><n0004>1921</n0004><p8589>6049</p8589><p9094>4743</p9094><p9599>4222</p9599><p0004>3689</p0004></record>
<record><voornaam>Maarten</voornaam><geslacht>M</geslacht><t8306>12185</t8306><n8589>3552</n8589><n9094>2791</n9094><n9599>2216</n9599><n0004>1545</n0004><p8589>6563</p8589><p9094>4861</p9094><p9599>4064</p9599><p0004>2967</p0004></record>
<record><voornaam>Koen</voornaam><geslacht>M</geslacht><t8306>12144</t8306><n8589>2046</n8589><n9094>3158</n9094><n9599>3055</n9599><n0004>2450</n0004><p8589>3780</p8589><p9094>5500</p9094><p9599>5603</p9599><p0004>4705</p0004></record>
<record><voornaam>Wesley</voornaam><geslacht>M</geslacht><t8306>11456</t8306><n8589>2903</n8589><n9094>3306</n9094><n9599>2385</n9599><n0004>1751</n0004><p8589>5364</p8589><p9094>5758</p9094><p9599>4374</p9599><p0004>3362</p0004></record>
<record><voornaam>Danny</voornaam><geslacht>M</geslacht><t8306>11436</t8306><n8589>3707</n8589><n9094>2831</n9094><n9599>2051</n9599><n0004>939</n0004><p8589>6849</p8589><p9094>4931</p9094><p9599>3762</p9599><p0004>1803</p0004></record>
<record><voornaam>Melissa</voornaam><geslacht>V</geslacht><t8306>11363</t8306><n8589>1921</n8589><n9094>3686</n9094><n9599>3142</n9599><n0004>1716</n0004><p8589>3714</p8589><p9094>6745</p9094><p9599>6061</p9599><p0004>3461</p0004></record>
<record><voornaam>Tessa</voornaam><geslacht>V</geslacht><t8306>11291</t8306><n8589>1592</n8589><n9094>2753</n9094><n9599>2850</n9599><n0004>2716</n0004><p8589>3078</p8589><p9094>5038</p9094><p9599>5497</p9599><p0004>5478</p0004></record>
<record><voornaam>Femke</voornaam><geslacht>V</geslacht><t8306>11116</t8306><n8589>1507</n8589><n9094>1518</n9094><n9599>2713</n9599><n0004>3498</n0004><p8589>2913</p8589><p9094>2778</p9094><p9599>5233</p9599><p0004>7055</p0004></record>
<record><voornaam>Robert</voornaam><geslacht>M</geslacht><t8306>11094</t8306><n8589>3852</n8589><n9094>2989</n9094><n9599>1635</n9599><n0004>730</n0004><p8589>7117</p8589><p9094>5206</p9094><p9599>2999</p9599><p0004>1402</p0004></record>
<record><voornaam>David</voornaam><geslacht>M</geslacht><t8306>11093</t8306><n8589>2301</n8589><n9094>2251</n9094><n9599>2560</n9599><n0004>2154</n0004><p8589>4251</p8589><p9094>3921</p9094><p9599>4695</p9599><p0004>4136</p0004></record>
<record><voornaam>Chantal</voornaam><geslacht>V</geslacht><t8306>11072</t8306><n8589>3904</n8589><n9094>3053</n9094><n9599>1638</n9599><n0004>856</n0004><p8589>7548</p8589><p9094>5587</p9094><p9599>3159</p9599><p0004>1727</p0004></record>
<record><voornaam>Jesse</voornaam><geslacht>M</geslacht><t8306>11023</t8306><n8589>555</n8589><n9094>1779</n9094><n9599>3567</n9599><n0004>3453</n0004><p8589>1025</p8589><p9094>3099</p9094><p9599>6542</p9599><p0004>6631</p0004></record>
<record><voornaam>Esther</voornaam><geslacht>V</geslacht><t8306>10981</t8306><n8589>3521</n8589><n9094>2770</n9094><n9599>1816</n9599><n0004>1116</n0004><p8589>6807</p8589><p9094>5069</p9094><p9599>3503</p9599><p0004>2251</p0004></record>
<record><voornaam>Amber</voornaam><geslacht>V</geslacht><t8306>10778</t8306><n8589>602</n8589><n9094>1744</n9094><n9599>3516</n9599><n0004>3726</n0004><p8589>1164</p8589><p9094>3192</p9094><p9599>6782</p9599><p0004>7515</p0004></record>
<record><voornaam>Emma</voornaam><geslacht>V</geslacht><t8306>10665</t8306><n8589>738</n8589><n9094>1533</n9094><n9599>2996</n9599><n0004>3833</n0004><p8589>1427</p8589><p9094>2805</p9094><p9599>5779</p9599><p0004>7731</p0004></record>
<record><voornaam>Naomi</voornaam><geslacht>V</geslacht><t8306>10358</t8306><n8589>896</n8589><n9094>1955</n9094><n9599>3280</n9599><n0004>3012</n0004><p8589>1732</p8589><p9094>3578</p9094><p9599>6327</p9599><p0004>6075</p0004></record>
<record><voornaam>Jelle</voornaam><geslacht>M</geslacht><t8306>10306</t8306><n8589>1451</n8589><n9094>2200</n9094><n9599>3057</n9599><n0004>2424</n0004><p8589>2681</p8589><p9094>3832</p9094><p9599>5607</p9599><p0004>4655</p0004></record>
<record><voornaam>Mohamed</voornaam><geslacht>M</geslacht><t8306>10288</t8306><n8589>2585</n8589><n9094>2238</n9094><n9599>1888</n9599><n0004>1896</n0004><p8589>4776</p8589><p9094>3898</p9094><p9599>3463</p9599><p0004>3641</p0004></record>
<record><voornaam>Charlotte</voornaam><geslacht>V</geslacht><t8306>10162</t8306><n8589>2018</n8589><n9094>2645</n9094><n9599>2485</n9599><n0004>1901</n0004><p8589>3901</p8589><p9094>4840</p9094><p9599>4793</p9599><p0004>3834</p0004></record>
<record><voornaam>Julia</voornaam><geslacht>V</geslacht><t8306>10162</t8306><n8589>449</n8589><n9094>1168</n9094><n9599>3231</n9599><n0004>3801</n0004><p8589>868</p8589><p9094>2137</p9094><p9599>6232</p9599><p0004>7667</p0004></record>
<record><voornaam>Daniëlle</voornaam><geslacht>V</geslacht><t8306>10051</t8306><n8589>3004</n8589><n9094>2576</n9094><n9599>1935</n9599><n0004>1131</n0004><p8589>5808</p8589><p9094>4714</p9094><p9599>3732</p9599><p0004>2281</p0004></record>
<record><voornaam>Sven</voornaam><geslacht>M</geslacht><t8306>9997</t8306><n8589>1434</n8589><n9094>1897</n9094><n9599>2298</n9599><n0004>2755</n0004><p8589>2650</p8589><p9094>3304</p9094><p9599>4215</p9599><p0004>5290</p0004></record>
<record><voornaam>Elisabeth</voornaam><geslacht>V</geslacht><t8306>9962</t8306><n8589>2967</n8589><n9094>2539</n9094><n9599>1644</n9599><n0004>1213</n0004><p8589>5736</p8589><p9094>4646</p9094><p9599>3171</p9599><p0004>2447</p0004></record>
<record><voornaam>Fleur</voornaam><geslacht>V</geslacht><t8306>9855</t8306><n8589>809</n8589><n9094>1249</n9094><n9599>2082</n9599><n0004>4208</n0004><p8589>1564</p8589><p9094>2286</p9094><p9599>4016</p9599><p0004>8488</p0004></record>
<record><voornaam>Eline</voornaam><geslacht>V</geslacht><t8306>9731</t8306><n8589>1422</n8589><n9094>2578</n9094><n9599>2575</n9599><n0004>2056</n0004><p8589>2749</p8589><p9094>4718</p9094><p9599>4967</p9599><p0004>4147</p0004></record>
<record><voornaam>Sophie</voornaam><geslacht>V</geslacht><t8306>9688</t8306><n8589>1030</n8589><n9094>1716</n9094><n9599>2438</n9599><n0004>2869</n0004><p8589>1991</p8589><p9094>3140</p9094><p9599>4703</p9599><p0004>5787</p0004></record>
<record><voornaam>Denise</voornaam><geslacht>V</geslacht><t8306>9682</t8306><n8589>2469</n8589><n9094>2960</n9094><n9599>2221</n9599><n0004>1236</n0004><p8589>4773</p8589><p9094>5417</p9094><p9599>4284</p9599><p0004>2493</p0004></record>
<record><voornaam>Vincent</voornaam><geslacht>M</geslacht><t8306>9587</t8306><n8589>2732</n8589><n9094>2630</n9094><n9599>1852</n9599><n0004>1145</n0004><p8589>5048</p8589><p9094>4581</p9094><p9599>3397</p9599><p0004>2199</p0004></record>
<record><voornaam>Suzanne</voornaam><geslacht>V</geslacht><t8306>9552</t8306><n8589>3114</n8589><n9094>2426</n9094><n9599>1479</n9599><n0004>876</n0004><p8589>6020</p8589><p9094>4440</p9094><p9599>2853</p9599><p0004>1767</p0004></record>
<record><voornaam>Jordy</voornaam><geslacht>M</geslacht><t8306>9545</t8306><n8589>1517</n8589><n9094>2557</n9094><n9599>2953</n9599><n0004>1770</n0004><p8589>2803</p8589><p9094>4454</p9094><p9599>5416</p9599><p0004>3399</p0004></record>
<record><voornaam>Ilse</voornaam><geslacht>V</geslacht><t8306>9487</t8306><n8589>1875</n8589><n9094>1848</n9094><n9599>1879</n9599><n0004>2572</n0004><p8589>3625</p8589><p9094>3382</p9094><p9599>3624</p9599><p0004>5188</p0004></record>
<record><voornaam>Romy</voornaam><geslacht>V</geslacht><t8306>9441</t8306><n8589>557</n8589><n9094>1539</n9094><n9599>3633</n9599><n0004>2913</n0004><p8589>1077</p8589><p9094>2816</p9094><p9599>7008</p9599><p0004>5876</p0004></record>
<record><voornaam>Joyce</voornaam><geslacht>V</geslacht><t8306>9403</t8306><n8589>3068</n8589><n9094>2565</n9094><n9599>1474</n9599><n0004>843</n0004><p8589>5931</p8589><p9094>4694</p9094><p9599>2843</p9599><p0004>1700</p0004></record>
<record><voornaam>Kelly</voornaam><geslacht>V</geslacht><t8306>9389</t8306><n8589>2398</n8589><n9094>3549</n9094><n9599>2180</n9599><n0004>697</n0004><p8589>4636</p8589><p9094>6495</p9094><p9599>4205</p9599><p0004>1406</p0004></record>
<record><voornaam>Lucas</voornaam><geslacht>M</geslacht><t8306>9349</t8306><n8589>843</n8589><n9094>1262</n9094><n9599>1767</n9599><n0004>3638</n0004><p8589>1558</p8589><p9094>2198</p9094><p9599>3241</p9599><p0004>6986</p0004></record>
<record><voornaam>Peter</voornaam><geslacht>M</geslacht><t8306>9198</t8306><n8589>3389</n8589><n9094>2096</n9094><n9599>1183</n9599><n0004>689</n0004><p8589>6262</p8589><p9094>3651</p9094><p9599>2170</p9599><p0004>1323</p0004></record>
<record><voornaam>Stijn</voornaam><geslacht>M</geslacht><t8306>9187</t8306><n8589>659</n8589><n9094>1287</n9094><n9599>2414</n9599><n0004>3334</n0004><p8589>1218</p8589><p9094>2242</p9094><p9599>4427</p9599><p0004>6402</p0004></record>
<record><voornaam>Joey</voornaam><geslacht>M</geslacht><t8306>9183</t8306><n8589>1331</n8589><n9094>2879</n9094><n9599>2264</n9599><n0004>1893</n0004><p8589>2459</p8589><p9094>5014</p9094><p9599>4152</p9599><p0004>3635</p0004></record>
<record><voornaam>Frank</voornaam><geslacht>M</geslacht><t8306>9179</t8306><n8589>3469</n8589><n9094>2204</n9094><n9599>1414</n9599><n0004>649</n0004><p8589>6410</p8589><p9094>3839</p9094><p9599>2593</p9599><p0004>1246</p0004></record>
<record><voornaam>Luuk</voornaam><geslacht>M</geslacht><t8306>9169</t8306><n8589>784</n8589><n9094>1554</n9094><n9599>2398</n9599><n0004>3022</n0004><p8589>1449</p8589><p9094>2707</p9094><p9599>4398</p9599><p0004>5803</p0004></record>
<record><voornaam>Manon</voornaam><geslacht>V</geslacht><t8306>8980</t8306><n8589>1662</n8589><n9094>2896</n9094><n9599>2252</n9599><n0004>1344</n0004><p8589>3213</p8589><p9094>5300</p9094><p9599>4344</p9599><p0004>2711</p0004></record>
<record><voornaam>Maaike</voornaam><geslacht>V</geslacht><t8306>8968</t8306><n8589>2146</n8589><n9094>1928</n9094><n9599>1969</n9599><n0004>1597</n0004><p8589>4149</p8589><p9094>3528</p9094><p9599>3798</p9599><p0004>3221</p0004></record>
<record><voornaam>Joost</voornaam><geslacht>M</geslacht><t8306>8856</t8306><n8589>2105</n8589><n9094>2192</n9094><n9599>1881</n9599><n0004>1389</n0004><p8589>3889</p8589><p9094>3818</p9094><p9599>3450</p9599><p0004>2667</p0004></record>
<record><voornaam>Merel</voornaam><geslacht>V</geslacht><t8306>8833</t8306><n8589>1333</n8589><n9094>1715</n9094><n9599>2266</n9599><n0004>2419</n0004><p8589>2577</p8589><p9094>3138</p9094><p9599>4371</p9599><p0004>4879</p0004></record>
<record><voornaam>Alexander</voornaam><geslacht>M</geslacht><t8306>8569</t8306><n8589>2406</n8589><n9094>2305</n9094><n9599>1463</n9599><n0004>1015</n0004><p8589>4445</p8589><p9094>4015</p9094><p9599>2683</p9599><p0004>1949</p0004></record>
<record><voornaam>Daphne</voornaam><geslacht>V</geslacht><t8306>8568</t8306><n8589>1689</n8589><n9094>1884</n9094><n9599>2573</n9599><n0004>1457</n0004><p8589>3265</p8589><p9094>3448</p9094><p9599>4963</p9599><p0004>2939</p0004></record>
<record><voornaam>Gerrit</voornaam><geslacht>M</geslacht><t8306>8533</t8306><n8589>2348</n8589><n9094>1950</n9094><n9599>1574</n9599><n0004>1208</n0004><p8589>4338</p8589><p9094>3396</p9094><p9599>2887</p9599><p0004>2320</p0004></record>
<record><voornaam>Sebastiaan</voornaam><geslacht>M</geslacht><t8306>8340</t8306><n8589>2267</n8589><n9094>2217</n9094><n9599>1498</n9599><n0004>1071</n0004><p8589>4189</p8589><p9094>3861</p9094><p9599>2747</p9599><p0004>2057</p0004></record>
<record><voornaam>Mandy</voornaam><geslacht>V</geslacht><t8306>8307</t8306><n8589>2473</n8589><n9094>2729</n9094><n9599>1608</n9599><n0004>875</n0004><p8589>4781</p8589><p9094>4994</p9094><p9599>3102</p9599><p0004>1765</p0004></record>
<record><voornaam>Erik</voornaam><geslacht>M</geslacht><t8306>8280</t8306><n8589>3233</n8589><n9094>1967</n9094><n9599>1084</n9599><n0004>582</n0004><p8589>5973</p8589><p9094>3426</p9094><p9599>1988</p9599><p0004>1118</p0004></record>
<record><voornaam>Nina</voornaam><geslacht>V</geslacht><t8306>8248</t8306><n8589>847</n8589><n9094>1364</n9094><n9599>2398</n9599><n0004>2614</n0004><p8589>1637</p8589><p9094>2496</p9094><p9599>4625</p9599><p0004>5272</p0004></record>
<record><voornaam>Britt</voornaam><geslacht>V</geslacht><t8306>8213</t8306><n8589>449</n8589><n9094>1099</n9094><n9599>2175</n9599><n0004>3399</n0004><p8589>868</p8589><p9094>2011</p9094><p9599>4195</p9599><p0004>6856</p0004></record>
<record><voornaam>Lisanne</voornaam><geslacht>V</geslacht><t8306>8187</t8306><n8589>1346</n8589><n9094>2504</n9094><n9599>2460</n9599><n0004>1392</n0004><p8589>2602</p8589><p9094>4582</p9094><p9599>4745</p9599><p0004>2808</p0004></record>
<record><voornaam>Sharon</voornaam><geslacht>V</geslacht><t8306>8176</t8306><n8589>2056</n8589><n9094>2611</n9094><n9599>2026</n9599><n0004>793</n0004><p8589>3975</p8589><p9094>4778</p9094><p9599>3908</p9599><p0004>1599</p0004></record>
<record><voornaam>Demi</voornaam><geslacht>V</geslacht><t8306>8158</t8306><n8589>13</n8589><n9094>645</n9094><n9599>3752</n9599><n0004>2995</n0004><p8589>25</p8589><p9094>1180</p9094><p9599>7237</p9599><p0004>6041</p0004></record>
<record><voornaam>Jessica</voornaam><geslacht>V</geslacht><t8306>8102</t8306><n8589>2331</n8589><n9094>2217</n9094><n9599>1685</n9599><n0004>684</n0004><p8589>4506</p8589><p9094>4057</p9094><p9599>3250</p9599><p0004>1380</p0004></record>
<record><voornaam>Samantha</voornaam><geslacht>V</geslacht><t8306>8092</t8306><n8589>2884</n8589><n9094>2538</n9094><n9599>1342</n9599><n0004>671</n0004><p8589>5576</p8589><p9094>4645</p9094><p9599>2589</p9599><p0004>1353</p0004></record>
<record><voornaam>Wendy</voornaam><geslacht>V</geslacht><t8306>8038</t8306><n8589>3352</n8589><n9094>1703</n9094><n9599>782</n9599><n0004>453</n0004><p8589>6480</p8589><p9094>3117</p9094><p9599>1508</p9599><p0004>914</p0004></record>
<record><voornaam>Lieke</voornaam><geslacht>V</geslacht><t8306>7943</t8306><n8589>1262</n8589><n9094>1375</n9094><n9599>1437</n9599><n0004>2183</n0004><p8589>2440</p8589><p9094>2516</p9094><p9599>2772</p9599><p0004>4403</p0004></record>
<record><voornaam>Nienke</voornaam><geslacht>V</geslacht><t8306>7936</t8306><n8589>1379</n8589><n9094>1511</n9094><n9599>1727</n9599><n0004>2001</n0004><p8589>2666</p8589><p9094>2765</p9094><p9599>3331</p9599><p0004>4036</p0004></record>
<record><voornaam>Richard</voornaam><geslacht>M</geslacht><t8306>7925</t8306><n8589>3004</n8589><n9094>2125</n9094><n9599>997</n9599><n0004>430</n0004><p8589>5550</p8589><p9094>3701</p9094><p9599>1829</p9599><p0004>826</p0004></record>
<record><voornaam>Remco</voornaam><geslacht>M</geslacht><t8306>7924</t8306><n8589>2249</n8589><n9094>2027</n9094><n9599>1666</n9599><n0004>837</n0004><p8589>4155</p8589><p9094>3530</p9094><p9599>3055</p9599><p0004>1607</p0004></record>
<record><voornaam>Marieke</voornaam><geslacht>V</geslacht><t8306>7868</t8306><n8589>2420</n8589><n9094>1580</n9094><n9599>1379</n9599><n0004>878</n0004><p8589>4679</p8589><p9094>2891</p9094><p9599>2660</p9599><p0004>1771</p0004></record>
<record><voornaam>Dylan</voornaam><geslacht>M</geslacht><t8306>7708</t8306><n8589>177</n8589><n9094>1736</n9094><n9599>2406</n9599><n0004>2511</n0004><p8589>327</p8589><p9094>3024</p9094><p9599>4413</p9599><p0004>4822</p0004></record>
<record><voornaam>Dirk</voornaam><geslacht>M</geslacht><t8306>7560</t8306><n8589>1933</n8589><n9094>1749</n9094><n9599>1499</n9599><n0004>1160</n0004><p8589>3572</p8589><p9094>3046</p9094><p9599>2749</p9599><p0004>2228</p0004></record>
<record><voornaam>Sarah</voornaam><geslacht>V</geslacht><t8306>7517</t8306><n8589>1176</n8589><n9094>1549</n9094><n9599>1692</n9599><n0004>1904</n0004><p8589>2274</p8589><p9094>2835</p9094><p9599>3264</p9599><p0004>3840</p0004></record>
<record><voornaam>Justin</voornaam><geslacht>M</geslacht><t8306>7417</t8306><n8589>644</n8589><n9094>1372</n9094><n9599>2048</n9599><n0004>2465</n0004><p8589>1190</p8589><p9094>2390</p9094><p9599>3756</p9599><p0004>4734</p0004></record>
<record><voornaam>Nicole</voornaam><geslacht>V</geslacht><t8306>7411</t8306><n8589>2468</n8589><n9094>1958</n9094><n9599>1159</n9599><n0004>598</n0004><p8589>4771</p8589><p9094>3583</p9094><p9599>2236</p9599><p0004>1206</p0004></record>
<record><voornaam>Paul</voornaam><geslacht>M</geslacht><t8306>7375</t8306><n8589>2699</n8589><n9094>1821</n9094><n9599>918</n9599><n0004>478</n0004><p8589>4987</p8589><p9094>3172</p9094><p9599>1684</p9599><p0004>918</p0004></record>
<record><voornaam>Matthijs</voornaam><geslacht>M</geslacht><t8306>7362</t8306><n8589>1298</n8589><n9094>1720</n9094><n9599>1797</n9599><n0004>1551</n0004><p8589>2398</p8589><p9094>2996</p9094><p9599>3296</p9599><p0004>2978</p0004></record>
<record><voornaam>Cornelia</voornaam><geslacht>V</geslacht><t8306>7257</t8306><n8589>2168</n8589><n9094>1702</n9094><n9599>1257</n9599><n0004>857</n0004><p8589>4191</p8589><p9094>3115</p9094><p9599>2425</p9599><p0004>1729</p0004></record>
<record><voornaam>Vera</voornaam><geslacht>V</geslacht><t8306>7062</t8306><n8589>885</n8589><n9094>1556</n9094><n9599>1908</n9599><n0004>1781</n0004><p8589>1711</p8589><p9094>2848</p9094><p9599>3680</p9599><p0004>3592</p0004></record>